- name: Install base package
  apt:
    name: ifupdown
    state: present

- name: Interfaces directory
  file:
    path: /etc/network/interfaces.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Network configuration
  template:
    src: interface.j2
    dest: /etc/network/interfaces.d/he-ipv6.cfg
    owner: root
    group: root
    mode: 0644
  notify: reload he-ipv6

- name: Silence sit's log_ecn_error
  command: echo N > /sys/module/sit/parameters/log_ecn_error