---
- name: Download the Minio client
  get_url:
    url: "{{ minio_client_download_url }}"
    dest: "{{ minio_client_bin }}"
    owner: "root"
    group: "root"
    mode: 0755
  register: download_client
  until: download_client is succeeded
  retries: 5
  delay: 2

- name: Create /root/.mc dir
  file:
    path:  /root/.mc
    state: directory

- name: Copy mc config
  template:
    src: config.json.j2
    dest: /root/.mc/config.json
    owner: root
    group: root
    mode: 600
