---
- name: Create swapfile
  command: fallocate -l {{ swap_size }} /mnt/{{ swap_file }}

- name: Format the file for swap
  command: mkswap /mnt/{{ swap_file }}

- name: Enforce swap file permissions
  file: 
    path: /mnt/{{ swap_file }} 
    owner: root 
    group: root
    mode: 0600

- name: Add the file to the system as a swap file
  command: swapon /mnt/{{ swap_file }}

- name: Write swap entry in the fstab
  mount:
    name: none 
    src: /mnt/{{ swap_file }}
    fstype: swap 
    opts: sw 
    passno: 0 
    dump: 0 
    state: present
