---
- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart timesyncd
  service:
    name: systemd-timesyncd
    state: restarted

- name: clean packages
  command: dpkg -P `deborphan`
  ignore_errors: yes
