- name: Install tmpreaper
  apt:
    name: tmpreaper
    state: present
    install_recommends: no

- name: tmpreaper configuration
  template:
    src: tmpreaper/tmpreaper.conf.j2
    dest: /etc/tmpreaper.conf
    owner: root
    group: root
    mode: 0644